//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBibliotecaOnline2.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biblioteca
    {
        public int BibliotecaId { get; set; }
        public string Identificador { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int IdPais { get; set; }
        public int IdTipoBiblioteca { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual TipoBiblioteca TipoBiblioteca { get; set; }
    }
}
